version: "3.5"
services:
  backend_client:
    build: .
    volumes:
      - ./functions/src:/app/functions/src
      - ./functions/package.json:/app/functions/package.json
    ports:
      - 5002:5002
      - 4000:4000
      - 9099:9099
      - 8080:8080
      - 4400:4400
      - 4500:4500
    networks:
      - gateway
    
networks:
  gateway:
    name: gateway